In [ ]:
import torch
x_train = torch.FloatTensor([[1,1], [2,2], [3,3]])
y_train = torch.FloatTensor([[10], [20], [30]])
W = torch.randn([2,1], requires_grad=True)
b = torch.randn([1], requires_grad=True)
optimizer = torch.optim.SGD([W,b], lr=0.01)

# 딥러닝 1단계 : 모델을 만든다. Model Setup
def H(x):
    model = torch.matmul(x,W)+b
    return model

# 딥러닝 2단계 : 모델을 학습시킨다. Model Training
for iter in range(2000):
    cost = torch.mean((H(x_train)-y_train) ** 2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if iter % 100 == 0:
        print('[Iteration]', iter, '[Cost]', cost.detach().item())

# 딥러닝 3단계 : 추론을 수행한다. Interface
x_test = torch.FloatTensor([[4,4]])

model_result = H(x_test)
print(model_result)
print(model_result.detach())
print('[Interface]', model_result.detach().item())

[Iteration] 0 [Cost] 530.1670532226562
[Iteration] 100 [Cost] 0.5272718071937561
[Iteration] 200 [Cost] 0.31240129470825195
[Iteration] 300 [Cost] 0.1850939244031906
[Iteration] 400 [Cost] 0.10966599732637405
[Iteration] 500 [Cost] 0.06497589498758316
[Iteration] 600 [Cost] 0.0384976826608181
[Iteration] 700 [Cost] 0.02280936948955059
[Iteration] 800 [Cost] 0.013514245860278606
[Iteration] 900 [Cost] 0.008006901480257511
[Iteration] 1000 [Cost] 0.004744040314108133
[Iteration] 1100 [Cost] 0.002810827689245343
[Iteration] 1200 [Cost] 0.0016653492348268628
[Iteration] 1300 [Cost] 0.00098673056345433
[Iteration] 1400 [Cost] 0.0005846599233336747
[Iteration] 1500 [Cost] 0.0003463691391516477
[Iteration] 1600 [Cost] 0.000205220581847243
[Iteration] 1700 [Cost] 0.00012159353354945779
[Iteration] 1800 [Cost] 7.206828013295308e-05
[Iteration] 1900 [Cost] 4.2707586544565856e-05
tensor([[39.9902]], grad_fn=<AddBackward0>)
tensor([[39.9902]])
[Interface] 39.990177154541016


In [ ]:
print(H(x_test))

tensor([[39.9894]], grad_fn=<AddBackward0>)


# Binary Classification

In [ ]:
x_train = torch.FloatTensor([[1,2], [2,3], [3,4], [4,4], [5,3], [6,2]])
y_train = torch.FloatTensor([[0], [0], [0], [1], [1], [1]])
W = torch.randn([2,1], requires_grad=True)
b = torch.randn([1], requires_grad=True)
optimizer = torch.optim.SGD([W, b], lr=0.01)

# 모델을 만드는 함수 정의
def H(x):
    model = torch.sigmoid(torch.matmul(x, W) + b)
    return model

# 모델 학습
for iter in range(2000):
    cost = torch.mean((-1) * y_train * torch.log(H(x_train)) + (-1) * (1 - y_train) * torch.log(1 - H(x_train)))

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if iter % 100 == 0:
        print('[Iteration]', iter, '[Cost]', cost.detach().item())

# 딥러닝 3단계 : 추론을 수행한다. Interface
x_test = torch.FloatTensor([[7,1]])

model_result = H(x_test)
print(model_result)
print(model_result.detach())
print('[Interface Value]', model_result.detach().item())
print('[Interface Classification]', 'A+' if model_result.detach().item() > 0.5 else 'F')

[Iteration] 0 [Cost] 2.82038950920105
[Iteration] 100 [Cost] 0.5097655653953552
[Iteration] 200 [Cost] 0.4151585102081299
[Iteration] 300 [Cost] 0.3588506877422333
[Iteration] 400 [Cost] 0.3211253881454468
[Iteration] 500 [Cost] 0.2936347424983978
[Iteration] 600 [Cost] 0.2723827660083771
[Iteration] 700 [Cost] 0.2552403211593628
[Iteration] 800 [Cost] 0.24097032845020294
[Iteration] 900 [Cost] 0.22880299389362335
[Iteration] 1000 [Cost] 0.21823258697986603
[Iteration] 1100 [Cost] 0.2089114934206009
[Iteration] 1200 [Cost] 0.20059211552143097
[Iteration] 1300 [Cost] 0.19309256970882416
[Iteration] 1400 [Cost] 0.18627560138702393
[Iteration] 1500 [Cost] 0.18003563582897186
[Iteration] 1600 [Cost] 0.1742895245552063
[Iteration] 1700 [Cost] 0.1689707487821579
[Iteration] 1800 [Cost] 0.16402553021907806
[Iteration] 1900 [Cost] 0.15940947830677032
tensor([[1.0000]], grad_fn=<SigmoidBackward0>)
tensor([[1.0000]])
[Interface Value] 0.9999855756759644
[Interface Classification] A+


## 선형관계로 설명할 수 없는 경우

In [ ]:
x_train = torch.FloatTensor([[1,2], [2,3], [3,4], [4,4], [5,3], [6,2], [8,1]])
y_train = torch.FloatTensor([[0], [0], [0], [1], [1], [1], [0]])
W = torch.randn([2,1], requires_grad=True)
b = torch.randn([1], requires_grad=True)
optimizer = torch.optim.SGD([W, b], lr=0.01)

# 모델을 만드는 함수 정의
def H(x):
    model = torch.sigmoid(torch.matmul(x, W) + b)
    return model

# 모델 학습
for iter in range(2000):
    cost = torch.mean((-1) * y_train * torch.log(H(x_train)) + (-1) * (1 - y_train) * torch.log(1 - H(x_train)))
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if iter % 100 == 0:
        print('[Iteration]', iter, '[Cost]', cost.detach().item(), '[Cost]', cost_1.detach().item())


model_result = H(x_train)
print(model_result)
print(model_result.detach())
# print('[Interface Classification]', 'A+' if model_result.detach().item() > 0.5 else 'F')

print("\nTest\n")
# 딥러닝 3단계 : 추론을 수행한다. Interface
x_test = torch.FloatTensor([[7,1]])

model_result = H(x_test)
print(model_result)
print(model_result.detach())
print('[Interface Value]', model_result.detach().item())
print('[Interface Classification]', 'A+' if model_result.detach().item() > 0.5 else 'F')

[Iteration] 0 [Cost] 0.9457800984382629 [Cost] nan
[Iteration] 100 [Cost] 0.6171383261680603 [Cost] nan
[Iteration] 200 [Cost] 0.6101185083389282 [Cost] nan
[Iteration] 300 [Cost] 0.6070127487182617 [Cost] nan
[Iteration] 400 [Cost] 0.6048434972763062 [Cost] nan
[Iteration] 500 [Cost] 0.6029143333435059 [Cost] nan
[Iteration] 600 [Cost] 0.6010671854019165 [Cost] nan
[Iteration] 700 [Cost] 0.5992660522460938 [Cost] nan
[Iteration] 800 [Cost] 0.5975020527839661 [Cost] nan
[Iteration] 900 [Cost] 0.5957726836204529 [Cost] nan
[Iteration] 1000 [Cost] 0.5940765738487244 [Cost] nan
[Iteration] 1100 [Cost] 0.5924126505851746 [Cost] nan
[Iteration] 1200 [Cost] 0.5907804369926453 [Cost] nan
[Iteration] 1300 [Cost] 0.5891790390014648 [Cost] nan
[Iteration] 1400 [Cost] 0.5876073241233826 [Cost] nan
[Iteration] 1500 [Cost] 0.5860651135444641 [Cost] nan
[Iteration] 1600 [Cost] 0.584551215171814 [Cost] nan
[Iteration] 1700 [Cost] 0.5830650925636292 [Cost] nan
[Iteration] 1800 [Cost] 0.581606090068817